#!/usr/bin/env bash
set -euo pipefail

export EXPO_NO_DOTENV=1
export EXPO_PUBLIC_ENABLE_DEV_SERVER=1
export EXPO_PUBLIC_SERVER_URL=dev.vex.wtf
export VEX_ENABLE_DEV_BUILD=1
export EAS_BUILD_PROFILE=development
export VEX_APP_DISPLAY_NAME="${VEX_APP_DISPLAY_NAME:-Vex Developer}"
export VEX_IOS_BUNDLE_IDENTIFIER="${VEX_IOS_BUNDLE_IDENTIFIER:-chat.vex.mobile.dev}"
export VEX_IOS_DEVELOPMENT_TEAM="${VEX_IOS_DEVELOPMENT_TEAM:-UBG5MM55LT}"
export VEX_IOS_FLAVOR=dev
export VEX_IOS_FLAVOR_NAME=dev
export APP_BUNDLE_ID="$VEX_IOS_BUNDLE_IDENTIFIER"
export EXPECTED_IOS_BUNDLE_IDENTIFIER="$VEX_IOS_BUNDLE_IDENTIFIER"
