export { VexClient } from './client.ts'
export type { VexEvents } from './client.ts'
export type { RegisterResult, LoginResult } from './auth.ts'
export type { SendResult } from './mail.ts'
export type { VexError, VexErrorCode } from './errors.ts'
export { fromEvent } from './iterators.ts'
