const { withGradleProperties } = require("expo/config-plugins");

// Expo config plugin that pins three gradle.properties values to
// keep both debug and release builds happy:
//
// 1. JVM memory:
//    The default gradle.properties generated by `expo prebuild` sets
//    -Xmx2048m -XX:MaxMetaspaceSize=512m. That's insufficient for a
//    release build (Kotlin codegen for New Architecture + expo-updates
//    KSP + DEX merge across multiple architectures all run in parallel
//    under org.gradle.parallel=true and fight for Metaspace). Bluesky
//    uses the same -Xmx4096m / -XX:MaxMetaspaceSize=1024m values in
//    plugins/withGradleJVMHeapSizeIncrease.js.
//
// 2. Architecture matrix:
//    The default `reactNativeArchitectures` builds for ALL FOUR
//    architectures (armeabi-v7a, arm64-v8a, x86, x86_64). Two are
//    legacy: armeabi-v7a (32-bit ARM, virtually no device sold since
//    2018) and x86 (32-bit Intel, only ancient emulator images).
//    Trimming to arm64-v8a + x86_64 halves native compilation work
//    and memory pressure. For sideloaded internal APKs this is the
//    right set; for Play Store release, AAB handles per-ABI splitting
//    automatically so a fat APK is never needed.
//
// 3. configureondemand=false:
//    `expo run:android` invokes Gradle with `--configure-on-demand`,
//    which lazily configures projects only when they're strictly
//    needed for task execution. That breaks any native module that
//    registers a repository inside its own build.gradle for the root
//    project to resolve — notifee in particular adds a local
//    `node_modules/@notifee/react-native/android/libs` maven repo
//    via `rootProject.allprojects { repositories { maven { ... } } }`.
//    With configure-on-demand, `:notifee_react-native` isn't
//    configured early enough; `:app:processDebugResources` resolves
//    `app.notifee:core:+` before the local repo is registered and
//    fails with "no versions of app.notifee:core are available".
//    Release builds (which run plain `./gradlew assembleRelease`,
//    without the flag) work fine. Disabling configure-on-demand
//    project-wide makes both paths behave the same; the cost is a
//    marginally slower configuration phase that doesn't matter for
//    a project this size.

function setProperty(props, key, value) {
    const idx = props.findIndex((p) => p.type === "property" && p.key === key);
    if (idx !== -1) {
        props[idx].value = value;
    } else {
        props.push({ type: "property", key, value });
    }
}

module.exports = function withGradleMemory(config) {
    return withGradleProperties(config, (config) => {
        const props = config.modResults;
        setProperty(
            props,
            "org.gradle.jvmargs",
            "-Xmx4096m -XX:MaxMetaspaceSize=1024m",
        );
        setProperty(props, "reactNativeArchitectures", "arm64-v8a,x86_64");
        setProperty(props, "org.gradle.configureondemand", "false");
        return config;
    });
};
