const { withGradleProperties } = require("expo/config-plugins");

// Expo config plugin that bumps Gradle daemon JVM memory limits and
// trims the Android architecture matrix.
//
// Bluesky uses the same fix: plugins/withGradleJVMHeapSizeIncrease.js
// with identical -Xmx4096m/-XX:MaxMetaspaceSize=1024m values.
//
// JVM memory:
//   The default gradle.properties generated by `expo prebuild` sets
//   -Xmx2048m -XX:MaxMetaspaceSize=512m. That's insufficient for a
//   release build (Kotlin codegen for New Architecture + expo-updates
//   KSP + DEX merge across multiple architectures all run in parallel
//   under org.gradle.parallel=true and fight for Metaspace).
//
// Architecture matrix:
//   The default `reactNativeArchitectures` builds for ALL FOUR
//   architectures (armeabi-v7a, arm64-v8a, x86, x86_64). Two are
//   legacy: armeabi-v7a (32-bit ARM, virtually no device sold since
//   2018) and x86 (32-bit Intel, only ancient emulator images).
//   Trimming to arm64-v8a + x86_64 halves native compilation work
//   and memory pressure. For sideloaded internal APKs this is the
//   right set; for Play Store release, AAB handles per-ABI splitting
//   automatically so a fat APK is never needed.

function setProperty(props, key, value) {
    const idx = props.findIndex(
        (p) => p.type === "property" && p.key === key,
    );
    if (idx !== -1) {
        props[idx].value = value;
    } else {
        props.push({ type: "property", key, value });
    }
}

module.exports = function withGradleMemory(config) {
    return withGradleProperties(config, (config) => {
        const props = config.modResults;
        setProperty(
            props,
            "org.gradle.jvmargs",
            "-Xmx4096m -XX:MaxMetaspaceSize=1024m",
        );
        setProperty(props, "reactNativeArchitectures", "arm64-v8a,x86_64");
        return config;
    });
};
